name: Build, test and deploy webR

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:
  build:
    name: Build webR
    runs-on: ubuntu-latest
    container: ghcr.io/r-wasm/flang-wasm:main
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Set npm dist-tag to "next" if pre-release version
        if: contains(github.ref_name, '-dev') || contains(github.ref_name, '-rc')
        run: echo "DIST_TAG=next" >> $GITHUB_ENV
      - name: Install required system packages
        run: apt-get update && apt-get install -y gh jq sudo
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Install required R packages for building documentation
        run: Rscript -e 'install.packages(c("rmarkdown", "rvest"))'
      - name: Configure webR for flang
        env:
          EMFC: /opt/flang/host/bin/flang-new
        run: ./configure
      - name: Setup Emscripten PATH
        run: echo "/opt/emsdk:/opt/emsdk/upstream/emscripten" >> $GITHUB_PATH
      - name: Set Emscripten EM_NODE_JS
        run: echo "EM_NODE_JS=$(which node)" >> $GITHUB_ENV
      - name: Set the webR CDN URL as the BASE_URL
        run: echo "BASE_URL=https://ouseful-demos.github.io/jupyterlite-m348-demo/${{ github.ref_name }}/" > "$HOME/.webr-config.mk"
        shell: bash
      - name: Set versioning for main
        if: "contains(github.ref_name, 'main')"
        run: |
          SHA="${{github.event.pull_request.head.sha}}${{ github.sha }}"
          SHORT_SHA=${SHA:0:7}
          VER=$(node -p "require('./src/package.json').version")
          echo "version: ${VER}+${SHORT_SHA}"
          echo "WEBR_VERSION=${VER}+${SHORT_SHA}" >> "$HOME/.webr-config.mk"
          echo "WEBR_VERSION_TAG=latest" >> "$HOME/.webr-config.mk"
        shell: bash
      - name: Set versioning for tag
        if: "!contains(github.ref_name, 'main')"
        run: |
          VER=$(node -p "require('./src/package.json').version")
          echo "version: ${VER}"
          echo "WEBR_VERSION=${VER}" >> "$HOME/.webr-config.mk"
          echo "WEBR_VERSION_TAG=${{ github.ref_name }}" >> "$HOME/.webr-config.mk"
        shell: bash
      - name: Build all optional wasm libs
        env:
          EMSDK: /opt/emsdk
        run: cd libs && make all
      - name: Build webR
        env:
          EMSDK: /opt/emsdk
        run: make && make check-pr
        shell: bash
      - name: Build webR documentation
        run: cd src/docs && make
        shell: bash
      - name: Build npm package
        run: cd src && make package
      - name: Archive webR build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webr-dist
          path: |
            dist
      - name: Archive webR documentation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webr-docs
          path: |
            src/docs/_site
